### ISSUE TITLE
Incorrect headers order after apoc csv export in community edition 3.5.6

### ISSUE THREAD

**Issue by dljcollette** [neo4j-contrib/neo4j-apoc-procedures#1246]
CSV headers seem to misalign with values in the rows when exporting with APOC. The issue could be related to https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1188, however the issue is now happening on the community version. Also, the bug appeared after upgrading to apoc 3.5.0.4 and neo4j 3.5.6 but was non-existent with apoc 3.4.0.4 and neo4j 3.4.5.

## Expected Behavior
Headers/columns are displayed correctly in csv export.

## Actual Behavior
Headers/columns are in the wrong order for certain pieces of data. For example, _id, _labels and _key are correct but _style should include an object with css styles instead of 'Field'.

## Steps to reproduce
Running "CALL apoc.export.csv.all(null, {stream:true,batchSize:100}) YIELD data RETURN data;", gives:

|                                                                                                                                                                             | 
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------| 
| "_id","_labels","_key","_style","_type","allowed","name","_start","_end","_type","_key","_style" | 
| "0",":SomeLabel","name","Field","someType","","",,,,,                                                                                                               | 
| "20",":SomeOtherLabel","step","Field","someOtherType","","",,,,,                                                                                                    | 

## Versions

  - OS: MacOSX, Ubuntu
  - Neo4j: >= 3.5.6 community edition
  - Neo4j-Apoc: apoc-3.5.0.4-all.jar

**Comment by conker84** [comment]
Hi @dljcollette can you try with the last release? This should be fixed by #1192 
Thanks a lot!

**Comment by dljcollette** [comment]
HI @conker84, I'm using APOC 3.5.0.4 and Neo4J 3.5.7. What would be the last release?

**Comment by conker84** [comment]
Sorry I confused the last release version with the one for v 3.4 which is 3.4.0.7, let me investigate. I'll be back soon.

**Comment by conker84** [comment]
@dljcollette can you try with the following jar?
[apoc-3.5.0.5-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/3368790/apoc-3.5.0.5-all.jar.zip)

**Comment by dljcollette** [comment]
@conker84 thanks for the update. I've tried [3.5.0.5](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/3368790/apoc-3.5.0.5-all.jar.zip) but it doesn't fix the bug. Do you have any other possible solution?

**Comment by conker84** [comment]
@dljcollette Are you sure? I was able to reproduce the problem in my env and that jar fixed the problem. Can you share a sample of your dataset?

**Comment by conker84** [comment]
@dljcollette ping :)

**Comment by dljcollette** [comment]
@conker84 sorry, my client doesn't allow to share a sample. The bug seems to happen when a value represents an object string. I'll try to replace these values with a string and see if the bug still persists. Will keep you updated.

**Comment by conker84** [comment]
@dljcollette If I understood correctly you have a `_style` property inside a node and also a relationship?

**Comment by conker84** [comment]
@dljcollette if you try with this statements:
```
CREATE (f:User1:User {name:'foo',age:42,male:true,kids:['a','b','c']})-[:KNOWS]->(b:User {name:'bar',age:42}),(c:User {age:12})
CREATE (n:MyNode{foo: 'Foo', bar: 'Bar', id: 1, style: '{"background":{"image:"/img/MY-IMG.png"}}'})
```
Are they enought to reproduce the problem in your env?

**Comment by dljcollette** [comment]
@conker84 thanks. It works fine with your sample. However, I was able to create a dataset that I can share that allows to reproduce the issue when exporting all to csv. For example, the item with `key: "family:composition.composition"` has a style object and an `_end: "Composition"`. The value `"Composition"` should have been set for `name` instead of `_end`. Also the value for `name` and other key value pairing seem to be incorrect.

```
CREATE CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;
UNWIND [{_id:260, data:{_composition:"Children", name:"John", _key:"family:children.john"}}, {_id:280, data:{_composition:"Children", name:"Ben", _key:"family:children.ben"}}, {_id:300, data:{_composition:"Children", name:"Anna", _key:"family:children.anna"}}, {_id:80, data:{allowed:"Relation", _composition:"William", name:"RelationNode", _key:"family:children.relationNode"}}, {_id:360, data:{_composition:"Children", name:"Integer", _key:"family:children.integer"}}, {_id:140, data:{_composition:"Children", name:"Enum", _key:"family:children.enum"}}, {_id:620, data:{_composition:"Children", name:"Boolean", _key:"family:children.boolean"}}, {_id:660, data:{_composition:"Children", name:"Float", _key:"family:children.float"}}, {_id:220, data:{_composition:"Children", name:"Date", _key:"family:children.date"}}, {_id:40, data:{_composition:"Children", name:"Text", _key:"family:children.text"}}] as row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.data SET n:Tree:Children:Family;
UNWIND [{_id:380, data:{_style:"{\"bfollowing\":{\"color\":\"{{theme.colors.six.hard1}}\"},\"outer\":{\"color\":\"{{theme.colors.six.default}}\"},\"text\":{\"color\":\"{{theme.colors.six.hard1}}\"}}", name:"Children", _composition:"Composition", _key:"family:composition.children"}}, {_id:440, data:{_style:"{\"bfollowing\":{\"color\":\"{{theme.colors.two.hard1}}\"},\"outer\":{\"color\":\"{{theme.colors.two.default}}\"},\"text\":{\"color\":\"{{theme.colors.two.hard1}}\"}}", _composition:"Composition", name:"Composition", _key:"family:composition.composition"}}, {_id:160, data:{_style:"{\"bfollowing\":{\"color\":\"{{theme.colors.three.hard1}}\"},\"outer\":{\"color\":\"{{theme.colors.three.default}}\"},\"text\":{\"color\":\"{{theme.colors.three.hard1}}\"}}", name:"House", _composition:"Composition", _key:"family:composition.house"}}, {_id:600, data:{_style:"{\"bfollowing\":{\"color\":\"{{theme.colors.one.hard1}}\"},\"outer\":{\"color\":\"{{theme.colors.one.default}}\"},\"text\":{\"color\":\"{{theme.colors.one.hard1}}\"}}", name:"Hierarchy", _composition:"Composition", _key:"family:composition.hierarchy"}}, {_id:640, data:{_style:"{\"bfollowing\":{\"color\":\"{{theme.colors.five.hard1}}\"},\"outer\":{\"color\":\"{{theme.colors.five.default}}\"},\"text\":{\"color\":\"{{theme.colors.five.hard1}}\"}}", name:"Relation", _composition:"Composition", _key:"family:composition.relation"}}] as row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.data SET n:Composition:Tree:Family;
UNWIND [{_id:60, data:{_composition:"House", name:"options", _key:"family:house.enum.options"}}, {_id:340, data:{_composition:"House", name:"default", _key:"family:house.has-house.default"}}, {_id:100, data:{_composition:"House", name:"allowed", _key:"family:house.node.allowed"}}, {_id:120, data:{_composition:"House", name:"following", _key:"family:house.has-house.following"}}, {_id:400, data:{name:"name", _composition:"House", _key:"family:house.name"}}, {_id:420, data:{_composition:"House", name:"present", _key:"family:house.has-house.present"}}, {_id:460, data:{_composition:"House", name:"disabled", _key:"family:house.has-house.disabled"}}, {_id:480, data:{_composition:"House", name:"help", _key:"family:house.has-house.help"}}, {_id:500, data:{name:"label", _composition:"House", _key:"family:house.label"}}, {_id:520, data:{_composition:"House", name:"min", _key:"family:house.kids.min"}}, {_id:560, data:{_composition:"House", name:"collection", _key:"family:house.has-house.collection"}}, {_id:200, data:{_composition:"House", name:"max", _key:"family:house.kids.max"}}, {_id:0, data:{_composition:"House", name:"step", _key:"family:house.kids.step"}}, {_id:20, data:{_composition:"House", name:"mustHave", _key:"family:house.has-house.mustHave"}}] as row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.data SET n:House:Tree:Family;
UNWIND [{_id:540, data:{_composition:"Hierarchy", name:"Family", _key:"family:hierarchy.family"}}] as row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.data SET n:Hierarchy:Tree:Family;
UNWIND [{_id:320, data:{_composition:"Relation", name:"HasRelation", _key:"family:relation.relation"}}, {_id:580, data:{_composition:"Relation", name:"HasChildren", _key:"family:relation.children"}}, {_id:180, data:{_composition:"Relation", name:"HasHouse", _key:"family:relation.house"}}, {_id:240, data:{_composition:"Relation", name:"HasComposition", _key:"family:relation.composition"}}] as row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.data SET n:Relation:Tree:Family;
UNWIND [{start: {_id:160}, end: {_id:380}, data:{_style:"{\"line\":{\"color\":\"{{theme.colors.four.default}}\"},\"text\":{\"color\":\"{{theme.colors.four.default}}\"},\"arrowTo\":{\"color\":\"{{theme.colors.four.default}}\"}}", name:"HasChildren", _key:"family:relation.house---family:composition.children"}}, {start: {_id:440}, end: {_id:440}, data:{_style:"{\"line\":{\"color\":\"{{theme.colors.two.default}}\"},\"text\":{\"color\":\"{{theme.colors.two.default}}\"},\"arrowTo\":{\"color\":\"{{theme.colors.two.default}}\"}}", name:"HasRelation", _key:"family:composition.composition---family:composition.composition"}}, {start: {_id:440}, end: {_id:160}, data:{_style:"{\"line\":{\"color\":\"{{theme.colors.three.default}}\"},\"text\":{\"color\":\"{{theme.colors.three.default}}\"},\"arrowTo\":{\"color\":\"{{theme.colors.three.default}}\"}}", name:"HasHouse", _key:"family:relation.composition---family:composition.house"}}, {start: {_id:600}, end: {_id:440}, data:{_style:"{\"line\":{\"color\":\"{{theme.colors.one.default}}\"},\"text\":{\"color\":\"{{theme.colors.one.default}}\"},\"arrowTo\":{\"color\":\"{{theme.colors.one.default}}\"}}", name:"HasComposition", _key:"family:composition.hierarchy---family:composition.composition"}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HasRelation]->(end) SET r += row.data;
UNWIND [{start: {_id:540}, end: {_id:220}, data:{_key:"family:hierarchy.family---family:children.date"}}, {start: {_id:540}, end: {_id:40}, data:{_key:"family:hierarchy.family---family:children.text"}}, {start: {_id:540}, end: {_id:280}, data:{_key:"family:hierarchy.family---family:children.node"}}, {start: {_id:540}, end: {_id:660}, data:{_key:"family:hierarchy.family---family:children.float"}}, {start: {_id:540}, end: {_id:360}, data:{_key:"family:hierarchy.family---family:children.integer"}}, {start: {_id:540}, end: {_id:620}, data:{_key:"family:hierarchy.family---family:children.boolean"}}, {start: {_id:540}, end: {_id:260}, data:{_key:"family:hierarchy.family---family:children.kids"}}, {start: {_id:540}, end: {_id:140}, data:{_key:"family:hierarchy.family---family:children.enum"}}, {start: {_id:540}, end: {_id:300}, data:{_key:"family:hierarchy.family---family:children.datetime"}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HasChildren]->(end) SET r += row.data;
UNWIND [{start: {_id:180}, end: {_id:20}, data:{help:"Some help text", present:false, label:"MustHave", collection:false, _key:"family:relation.house---family:house.has-house.mustHave", mustHave:false, following:3}}, {start: {_id:180}, end: {_id:340}, data:{help:"Some help text", present:false, label:"Default value", collection:false, _key:"family:relation.house---family:house.has-house.default", mustHave:false, following:7}}, {start: {_id:320}, end: {_id:500}, data:{help:"Some help text", present:true, label:"Label", collection:false, _key:"family:relation.relation--family:house.label", mustHave:false, following:0}}, {start: {_id:180}, end: {_id:560}, data:{help:"Some help text.", present:false, collection:false, label:"Multiple values", _key:"family:relation:house---family:house.has-house.collection", mustHave:false, following:4}}, {start: {_id:180}, end: {_id:120}, data:{help:"Some help text.", present:false, label:"Following", collection:false, _key:"family:relation.house---family:house.has-house.following", mustHave:false, following:8}}, {start: {_id:180}, end: {_id:420}, data:{help:"Some help text.", default:false, present:false, collection:false, label:"Preview changes", _key:"family:relation:house---family:house.has-house.present", mustHave:false, following:6}}, {start: {_id:580}, end: {_id:500}, data:{help:"Some help text.", present:true, label:"Label", collection:false, _key:"family:relation.children--family:house.label", mustHave:false, following:0}}, {start: {_id:180}, end: {_id:460}, data:{help:"Some help text.", label:"Read only", collection:false, _key:"family:composition:house---family:house.has-house.disabled", mustHave:false, following:5}}, {start: {_id:240}, end: {_id:500}, data:{help:"Some help text.", present:true, label:"Label", collection:false, _key:"family:relation.composition---family:house.label", mustHave:false, following:0}}, {start: {_id:180}, end: {_id:400}, data:{help:"Some help text.", present:false, label:"Name", collection:false, _key:"family:relation.house----family:house.name", mustHave:true, following:0}}, {start: {_id:180}, end: {_id:480}, data:{help:"Some help text.", present:false, label:"Description", collection:false, _key:"family:relation.house---family:house.has-house.help", mustHave:false, following:2}}, {start: {_id:180}, end: {_id:500}, data:{help:"Some help text.", present:true, label:"Label", collection:false, _key:"family:relation.house---family:house.label", mustHave:false, following:1}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HasHouse]->(end) SET r += row.data;
UNWIND [{start: {_id:340}, end: {_id:40}, data:{_key:"family:house.has-house.default---family:children.text"}}, {start: {_id:420}, end: {_id:620}, data:{_key:"family:house.has-house.present---family:children.text"}}, {start: {_id:480}, end: {_id:40}, data:{_key:"family:house.has-house.help---family:children.text"}}, {start: {_id:60}, end: {_id:40}, data:{_key:"family:house.enum.options---family:children.text"}}, {start: {_id:400}, end: {_id:40}, data:{_key:"family:house.name---family:children.text"}}, {start: {_id:0}, end: {_id:660}, data:{_key:"family:house.kids.step---family:children.float"}}, {start: {_id:100}, end: {_id:280}, data:{_key:"family:house.node.allowed---family:children.node"}}, {start: {_id:460}, end: {_id:620}, data:{_key:"family:house.has-house.disabled---family:children.text"}}, {start: {_id:200}, end: {_id:660}, data:{_key:"family:house.kids.max---family:children.float"}}, {start: {_id:20}, end: {_id:620}, data:{_key:"family:house.has-house.mustHave---family:children.text"}}, {start: {_id:120}, end: {_id:360}, data:{_key:"family:house.has-house.following---family:children.integer"}}, {start: {_id:520}, end: {_id:660}, data:{_key:"family:house.kids.min---family:children.float"}}, {start: {_id:560}, end: {_id:620}, data:{_key:"family:house.has-house.collection---family:children.text"}}, {start: {_id:500}, end: {_id:40}, data:{_key:"family:house.label---family:children.text"}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HasChildren]->(end) SET r += row.data;
UNWIND [{start: {_id:320}, end: {_id:80}, data:{help:"Some help text", present:false, label:"EdgeComposition", collection:false, _key:"family:relation.relation--family:children.relationNode", mustHave:false, following:0}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HasHouse]->(end) SET r += row.data;
UNWIND [{start: {_id:540}, end: {_id:640}, data:{_key:"family:hierarchy.family---family:composition.relation"}}, {start: {_id:540}, end: {_id:160}, data:{_key:"family:hierarchy.family---family:composition.house"}}, {start: {_id:540}, end: {_id:600}, data:{_key:"family:hierarchy.family---family:composition.hierarchy"}}, {start: {_id:540}, end: {_id:440}, data:{_key:"family:hierarchy.family---family:composition.composition"}}, {start: {_id:540}, end: {_id:380}, data:{_key:"family:hierarchy.family---family:composition.children"}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HasComposition]->(end) SET r += row.data;
UNWIND [{start: {_id:260}, end: {_id:0}, data:{help:"Some help text", present:false, label:"Step", collection:true, _key:"family:children.kids---family:house.kids.step", mustHave:false, following:3}}, {start: {_id:140}, end: {_id:400}, data:{help:"Some help text", present:false, label:"Name", collection:false, _key:"family:children.enum---family:house.name", mustHave:true, following:0}}, {start: {_id:260}, end: {_id:200}, data:{help:"Some help text", present:false, label:"Maximum", collection:true, _key:"family:children.kids---family:house.kids.max", mustHave:false, following:2}}, {start: {_id:280}, end: {_id:100}, data:{help:"Some help text", present:false, label:"Allowed compositions", collection:true, _key:"family:children.node---family:house.node.allowed", mustHave:false, following:0}}, {start: {_id:280}, end: {_id:400}, data:{help:"Some help text.", present:false, label:"Name", collection:false, _key:"family:children.node---family:house.name", mustHave:true, following:0}}, {start: {_id:140}, end: {_id:60}, data:{help:"Some help text.", present:false, label:"Options", collection:true, _key:"family:children.enum---family:house.enum.options", mustHave:false, following:1}}, {start: {_id:260}, end: {_id:400}, data:{help:"Some help text.", present:false, label:"Name", collection:false, _key:"family:children.kids---family:house.name", mustHave:true, following:0}}, {start: {_id:260}, end: {_id:520}, data:{help:"Some help text.", present:false, label:"Minimum", collection:true, _key:"family:children.kids---family:house.kids.min", mustHave:false, following:1}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HasHouse]->(end) SET r += row.data;
UNWIND [{start: {_id:540}, end: {_id:580}, data:{_key:"family:hierarchy.family---family:relation.children"}}, {start: {_id:540}, end: {_id:180}, data:{_key:"family:hierarchy.family---family:relation.house"}}, {start: {_id:540}, end: {_id:240}, data:{_key:"family:hierarchy.family---family:relation.composition"}}, {start: {_id:540}, end: {_id:320}, data:{_key:"family:hierarchy.family---family:relation.relation"}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HasComposition]->(end) SET r += row.data;
UNWIND [{start: {_id:440}, end: {_id:400}, data:{help:"Some help text", present:false, label:"Name", collection:false, _key:"family:composition.composition---family:house.name", mustHave:true, following:0}}, {start: {_id:640}, end: {_id:400}, data:{help:"Some help text", present:false, label:"Name", collection:false, _key:"family:composition.relation---family:house.name", mustHave:true, following:0}}, {start: {_id:600}, end: {_id:400}, data:{help:"Some help text", present:false, label:"Name", collection:false, _key:"family:composition.hierarchy---family:house.name", mustHave:true, following:0}}, {start: {_id:160}, end: {_id:400}, data:{help:"Some help text", present:false, label:"Name", collection:false, _key:"family:composition.house---family:house.name", mustHave:true, following:0}}, {start: {_id:380}, end: {_id:400}, data:{help:"Some help text.", present:false, label:"Name", collection:false, _key:"family:composition.children---family:house.name", mustHave:true, following:0}}] as row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HasHouse]->(end) SET r += row.data;
MATCH (n:`UNIQUE IMPORT LABEL`)  WITH n LIMIT 20000 REMOVE n:`UNIQUE IMPORT LABEL` REMOVE n.`UNIQUE IMPORT ID`;
DROP CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;

```

**Comment by conker84** [comment]
@dljcollette Thanks a lot, the following exported csv looks good to me, can you confirm that?
[export.csv.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/3388635/export.csv.zip)

**Comment by conker84** [comment]
@dljcollette ping :)
