### ISSUE TITLE
Bug: Can't use pairs in FOREACH

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#94]
The apoc.coll.pairs([list]) procedure looks ideal for creating linked lists of nodes, and seems like it should be easier to use than some kind of double FOREACH loop or iteration over an index. 

However, if we use the generated pairs in a FOREACH to try to match, merge, or create nodes based upon the list and link them up, we fail with an error.

Here is an example case:

```
WITH ["a", "b", "c", "d", "e"] as letters
CALL apoc.coll.pairs(letters) YIELD value as names
// last pair unnecessary, as it pairs the last element with null
WITH names[..SIZE(names)-1] as names
FOREACH (pair in names |
MERGE (a:Thing{name: pair[0]})
MERGE (b:Thing{name: pair[1]})
MERGE (a)-[:relates_to]->(b))
```

This fails with the following error:

`Type mismatch: expected Collection<T> but was Any
`
Attempting to use head(pair) or last(pair) returns the same error.

If instead of using pairs() we explicitly used [["a","b"],["b","c"],["c","d"],["d","e"]], it works fine:

```
WITH [["a","b"],["b","c"],["c","d"],["d","e"]] as names
FOREACH (pair in names |
MERGE (a:Thing{name: pair[0]})
MERGE (b:Thing{name: pair[1]})
MERGE (a)-[:relates_to]->(b))
```

Please fix when possible.

**Comment by jexp** [comment]
Fixed, there is now also an apoc.coll.pairsMin() which leaves off the last pair.

Please build locally, check and report back.

**Comment by InverseFalcon** [comment]
Built and tested, working as expected, including the new parisMin() function. Thanks!

If I can slip one additional suggestion, while this works beautifully for creating and connecting nodes, or matching on nodes and connecting them, I still don't think there's a way, given a collection of node objects, to link them all in list order directly (you can't do `MERGE ( (pair[0])-[:relates_to]->(pair[1]) )`, or use head() and last()).

A procedure that takes in a list of nodes, and creates a linked list out of them with the given relationship type between them would be nice to have.

**Comment by jexp** [comment]
I added a apoc.node.link for that, please have a look.

**Comment by InverseFalcon** [comment]
I'm not seeing that change on the master branch. Has it been committed yet?

**Comment by jexp** [comment]
see: https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/master/src/main/java/apoc/nodes/Nodes.java#L35

**Comment by InverseFalcon** [comment]
Works great!

So...do I close this, or do you?
